services:
  app:
    container_name: "nokuri_app"
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/app
    working_dir: /var/www/app
    ports:
      - 5173:5173
  nginx:
    container_name: "nokuri_nginx"
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf 
      - ./src:/var/www/app
    depends_on:
      - app
    ports:
      - 80:80