services:
  app:
    container_name: "api_nokuri_app"
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/app
    working_dir: /var/www/app
    ports:
      - 5173:5173
  nginx:
    container_name: "api_nokuri_nginx"
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf 
      - ./src:/var/www/app
    depends_on:
      - app
    ports:
      - 80:80
  mailhog:
    image: mailhog/mailhog
    platform: 'linux/amd64'
    ports:
      - target: 8025
        published: ${MAILHOG_PUBLISHED_PORT:-8025}
        protocol: tcp
        mode: host