name: sakura_develop_deploy

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - name: Checkout Repository
       uses: actions/checkout@v3

     # 自動デプロイ
     - name: develop deploy
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.SERVER_HOST }}
         username: ${{ secrets.SERVER_USERNAME }}
         password: ${{ secrets.SERVER_PASS }}
         script: |
           cd ${{ secrets.SERVER_DEPLOY_DIR }}
           git pull origin develop

     # PHPバージョン
     - name: php version
       run: php --version

     # データベース反映
     - name: db migrate
       uses: actions/checkout@v3
       with:
        script: |
          cd ${{ secrets.SERVER_DEPLOY_DIR }}/src
          php artisa migrate